-- ==============================================================================
-- BROWNS CAFE - RESET DATABASE AND IMPORT NEW ITEMS WITH CATEGORIES
-- Execute this SQL in your Supabase SQL Editor.
-- ==============================================================================

-- 1. Clear all items and automatically CASCADE-delete all transaction logs and balances
TRUNCATE TABLE public.items CASCADE;

-- 2. Clear all accounting periods to restart fresh.
TRUNCATE TABLE public.accounting_periods CASCADE;

-- 2.5 Drop strict unit constraints to allow the new variety of units (TIN, NOS, PKT, etc.)
ALTER TABLE public.items DROP CONSTRAINT IF EXISTS items_unit_check;

-- 3. Set up the starting period for March 2026
INSERT INTO public.accounting_periods (label, month, year, status)
VALUES ('MAR 2026', 'MAR', 2026, 'open');

-- 4. Insert customized fresh master item list with codes and categories
INSERT INTO public.items (item_code, name, unit, category, min_stock) VALUES
('RM 1000', 'MITY WHOLE KERNAL CORN (425G)-300', 'TIN', 'Dry Groceries', 5),
('RM1192', 'CREAM CORN( 425G)- 300', 'TIN', 'Dry Groceries', 5),
('RM1004', 'BAKED BEANS', 'TIN', 'Dry Groceries', 5),
('RM 1007', 'BULERIAS PITTED GREEN OLIVERS.(330G)-400', 'BOT', 'Dry Groceries', 5),
('RM 1008', 'BULERIAS BLACK PITTED OLIVERS (330G)-400', 'BOT', 'Dry Groceries', 5),
('RM 1024', 'SWISS BERAR MAYONNAISE (3L)-3300', 'LTR', 'Dry Groceries', 5),
('RM 1021', 'EDIN ARTIFIAL VINEGAR (750ML)-95', 'BOT', 'Dry Groceries', 5),
('RM 1025', 'EDIN MUSTARD CREAM PET (675G)345', 'BOT', 'Dry Groceries', 5),
('RM 1023', 'EDIN B B Q SAUCE (350ML)SQ2-350', 'BOT', 'Dry Groceries', 5),
('RM 1109', 'ITALIAN OLIVE OIL (1L)OPM-1430', 'LTR', 'Dry Groceries', 5),
('RM1203', 'SESAMI OIL', 'BOT', 'Dry Groceries', 5),
('RM1212', 'WORCESTERSURE SAUCE', 'BOT', 'Dry Groceries', 5),
('RM1016', 'SOYA SAUCE', 'LTR', 'Dry Groceries', 5),
('RM1196', 'PEACH HALFS', 'TIN', 'Dry Groceries', 5),
('RM 1110', 'RICH LIFE UHT MILK', 'PKT', 'Dairy', 5),
('RM 1111', 'RICH LIFE UHT MILK NON FAT', 'PKT', 'Dairy', 5),
('RM3001', 'FRESH MILK RAN KIRI', 'PKT', 'Dairy', 5),
('RM3002', 'HIGHLAND FRESH 500 ML', 'PKT', 'Dairy', 5),
('RM3003', 'KOTHMALE VANILA MILK PKT 180ML', 'PKT', 'Dairy', 5),
('RM3004', 'SOY MILK (200 ML)', 'BOT', 'Dairy', 5),
('SN332', 'POTATO CHIP- LARGE', 'PKT', 'Dry Groceries', 5),
('SN331', 'CASSAVA CHIP SALT & SEPPER 100G', 'PKT', 'Dry Groceries', 5),
('B070', 'ICE TEA BOTTLES', 'BOT', 'Beverages', 5),
('RM1112', 'CHOCOLATE ICE CREAM (2L)', '2 LTR', 'Dairy', 5),
('RM1113', 'VANILA ICE CREAM (2L)', '2LTR', 'Dairy', 5),
('RM1114', 'STRAWBERY ICE CREAM (2L)', '2LTR', 'Dairy', 5),
('IC352', '60ML WONDERBAR ICY CHOCK', 'NOS', 'Confectionery & Sweets', 5),
('IC351', '120MLWONDE BAR CORN', 'NOS', 'Confectionery & Sweets', 5),
('RM1099', 'TUBE ICE CUBE 1KG', 'PKT', 'Beverages', 5),
('RM1118', 'GRANOLA', 'KG', 'Dry Groceries', 5),
('RM3005', 'RIDE CLASSIC DRINK 250ML', 'BOT', 'Beverages', 5),
('B072', 'ALKA WATER BOTTLE', 'BOT', 'Beverages', 5),
('B075', 'STERLING WATER BOT ( GLASS BOT)', 'BOT', 'Beverages', 5),
('RM1119', 'CURD', 'TUB', 'Dairy', 5),
('RM1120', 'YOGURT', 'TUB', 'Dairy', 5),
('RM3006', 'YOGURT SMALL', 'NOS', 'Dairy', 5),
('RM1005', 'TUNA CAN (S) 140 GRM', 'CAN', 'Dry Groceries', 5),
('RM1006', 'SAMON SMALL', 'TIN', 'Dry Groceries', 5),
('RM2001', 'VEGETABLE OIL', 'LTR', 'Dry Groceries', 5),
('RM1026', 'TOMATO SAUCE', 'LTR', 'Dry Groceries', 5),
('RM1220', 'SWEET CHILLI SAUCE', 'BOT', 'Dry Groceries', 5),
('RM1028', 'OYESTA SOUSE ( )', 'BOT', 'Dry Groceries', 5),
('RM1029', 'LIME POWDER', 'PKT', 'Dry Groceries', 5),
('RM1209', 'KITUL TRICLE (750 ML)', 'BOT', 'Dry Groceries', 5),
('RM1210', 'JUGGARY', 'KG', 'Dry Groceries', 5),
('RM1031', 'MINCED CHICKEN NORFOLK', 'KG', 'Meat & Poultry', 5),
('RM1032', 'MINCED BEEF', 'KG', 'Meat & Poultry', 5),
('RM1036', 'CHICKEN /HAM', 'SLICE', 'Meat & Poultry', 5),
('RM1033', 'SMOK CHICKEN', 'KG', 'Meat & Poultry', 5),
('RM1034', 'PEPPER BEEF', 'KG', 'Meat & Poultry', 5),
('RM1035', 'CHICKEN BREST (1K)', 'KG', 'Meat & Poultry', 5),
('RM1215', 'CHICKEN WINGS', 'KG', 'Meat & Poultry', 5),
('RM1037', 'JUMBO SAUSAGES( 15 NOS)', 'NOS', 'Meat & Poultry', 5),
('RM1193', 'HOT DOGS (30 (NOS)', 'NOS', 'Meat & Poultry', 5),
('RM3063', 'CHICKEN BECON', 'SLICE', 'Meat & Poultry', 5),
('RM1214', 'SALAMI', 'KG', 'Meat & Poultry', 5),
('RM1198', 'BREAKFAST SAUSAGE (40 NOS)', 'NOS', 'Meat & Poultry', 5),
('RM1197', 'MEAT BALLS (60 NOS)', 'KG', 'Meat & Poultry', 5),
('RM3007', 'SOUP BONES', 'KG', 'Meat & Poultry', 5),
('RM1221', 'KOCHCHI SAUSAGE', 'NOS', 'Meat & Poultry', 5),
('RM1040', 'FISH FILLET', 'KG', 'Meat & Poultry', 5),
('RM1038', 'BEEF FILLET', 'KG', 'Meat & Poultry', 5),
('RM1041', 'CUTTLE FISH', 'KG', 'Meat & Poultry', 5),
('RM1039', 'PRAWNS', 'KG', 'Meat & Poultry', 5),
('RM1009', 'VANILA SYRUP (1L)', 'LTR', 'Beverages', 5),
('RM1010', 'CARAMEL SYRUP (1L)', 'LTR', 'Beverages', 5),
('RM1011', 'HEZALNUT SYRUP (1L)', 'LTR', 'Beverages', 5),
('RM1013', 'THIRAMISU SYRUP', 'LTR', 'Beverages', 5),
('RM1014', 'CARAMEL SAUCE (1.89 LTR)', 'LTR', 'Beverages', 5),
('RM1017', 'CHOCOLATE SAUCE HARSHEYS 750 ML', 'BOT', 'Beverages', 5),
('RM1018', 'STRAWBERRY SAUCE HARSHEYS 750 ML', 'BOT', 'Beverages', 5),
('E301', 'DOUGHNUT', 'NOS', 'Confectionery & Sweets', 5),
('E303', 'CUP CAKES', 'NOS', 'Confectionery & Sweets', 5),
('E304', 'BROWNIES', 'NOS', 'Confectionery & Sweets', 5),
('E344', 'BANANA CAKE', 'NOS', 'Confectionery & Sweets', 5),
('E346', 'DATE CAKE', 'NOS', 'Confectionery & Sweets', 5),
('E343', 'CARROT CAKE', 'NOS', 'Confectionery & Sweets', 5),
('E345', 'ROBBON CAKE', 'NOS', 'Confectionery & Sweets', 5),
('E308', 'HONEY', 'BOT', 'Confectionery & Sweets', 5),
('E309', 'BUTTER CAKE', 'NOS', 'Confectionery & Sweets', 5),
('E310', 'CHOCOLATE MOUSSE', 'NOS', 'Confectionery & Sweets', 5),
('E312', 'CHOCOLATE CROSSIANTS', 'NOS', 'Confectionery & Sweets', 5),
('E313', 'PUDDING SMALL', 'NOS', 'Confectionery & Sweets', 5),
('E314', 'CHIP COOKIES', 'NOS', 'Confectionery & Sweets', 5),
('E334', 'ECLAIRS', 'NOS', 'Confectionery & Sweets', 5),
('E322', 'MUFFINS', 'NOS', 'Confectionery & Sweets', 5),
('E323', 'CINNAMON ROLLS', 'NOS', 'Confectionery & Sweets', 5),
('E337', 'RED VELVET CUP CAKE', 'NOS', 'Confectionery & Sweets', 5),
('E338', 'CHOCOLATE CAKE', 'NOS', 'Confectionery & Sweets', 5),
('RM1224', 'BREDED BURGER PATTY', 'NOS', 'Meat & Poultry', 5),
('SW428', 'CHICKEN ROLLS', 'NOS', 'Confectionery & Sweets', 5),
('SW440', 'FISH ROLLS', 'NOS', 'Confectionery & Sweets', 5),
('SW468', 'VEG SPRING ROLLS', 'NOS', 'Confectionery & Sweets', 5),
('SW432', 'FISH BUN', 'NOS', 'Confectionery & Sweets', 5),
('SW427', 'FISH PESTRY', 'NOS', 'Confectionery & Sweets', 5),
('RM1056', 'COFFEE PACKETS(500)', 'GRM', 'Beverages', 5),
('RM1232', 'CHOCOLATE MOUSSE MIX 350 GRM PKT', 'PKT', 'Bakery Raw', 5),
('RM3008', 'ALUMINIUM FOIL', 'ROLL', 'Packaging & Disposables', 5),
('RM3009', 'GROCERY BAGS', 'NOS', 'Packaging & Disposables', 5),
('RM3010', 'SHOPPING BAGS', 'NOS', 'Packaging & Disposables', 5),
('RM1155', 'BROWN PAPER BAGS (M)', 'PKT', 'Packaging & Disposables', 5),
('RM1156', 'BROWN PAPER BAG (L)', 'KG', 'Packaging & Disposables', 5),
('RM1157', 'BROWN PAPER BAG (S)', 'KG', 'Packaging & Disposables', 5),
('RM1158', 'BOX BAG WITH LOGO', 'NOS', 'Packaging & Disposables', 5),
('RM3011', 'LARGE BOX BAG', 'KG', 'Packaging & Disposables', 5),
('RM1233', 'BURGER BOX', 'KG', 'Packaging & Disposables', 5),
('RM1159', 'POLITHEN GLOWS', 'KG', 'Packaging & Disposables', 5),
('RM1160', 'RUBBER GLOWS', 'KG', 'Packaging & Disposables', 5),
('RM3012', 'PRITING ROLL', 'NOS', 'Packaging & Disposables', 5),
('RM3013', 'VOUCHER BOOKS', 'NOS', 'Packaging & Disposables', 5),
('RM1161', 'OIL PAPER WITH LOGO', 'NOS', 'Packaging & Disposables', 5),
('RM3014', 'OIL PAPER', 'NOS', 'Packaging & Disposables', 5),
('RM1162', 'GARBAG BAG', 'PKT', 'Packaging & Disposables', 5),
('RM1163', 'STROW PACKETS', 'PKT', 'Packaging & Disposables', 5),
('RM1234', 'WRAPPED STROWS', 'NOS', 'Packaging & Disposables', 5),
('RM3015', 'CELO TAPE', 'ROLL', 'Packaging & Disposables', 5),
('RM1164', 'SOUP SPOONS', 'NOS', 'Packaging & Disposables', 5),
('RM3016', 'FRUIT SALADCUPS', 'NOS', 'Packaging & Disposables', 5),
('RM1166', 'SOUP CUPS', 'NOS', 'Packaging & Disposables', 5),
('RM3017', 'CHOCOLATE MOUSSE CUP', 'NOS', 'Packaging & Disposables', 5),
('RM1167', 'BROWNIE CONTAINER', 'NOS', 'Packaging & Disposables', 5),
('RM1168', 'BROWN BEENS COFFEE 400ML PAPER CUP', 'NOS', 'Packaging & Disposables', 5),
('RM3018', 'TEA CUPS WITH LID', 'NOS', 'Packaging & Disposables', 5),
('RM1169', 'COOL LIDS', 'NOS', 'Packaging & Disposables', 5),
('RM1170', 'SIPPER LIDS', 'NOS', 'Packaging & Disposables', 5),
('RM3019', 'SAUCE CUPS', 'NOS', 'Packaging & Disposables', 5),
('RM3020', 'BUTTER CUP', 'NOS', 'Packaging & Disposables', 5),
('RM3021', 'BAKE BEAN CUPS', 'NOS', 'Packaging & Disposables', 5),
('RM1174', 'PLASTIC FORKS/SPOONS', 'NOS', 'Packaging & Disposables', 5),
('RM3022', 'PLASTIC KNIVES', 'NOS', 'Packaging & Disposables', 5),
('RM1175', 'CUP CAKE BOX', 'NOS', 'Packaging & Disposables', 5),
('RM1176', 'CUP WITH DOME LID', 'NOS', 'Packaging & Disposables', 5),
('RM3023', 'TOOTH PICKS', 'PKT', 'Packaging & Disposables', 5),
('RM1177', 'PEPER SERVIETTS', 'PKT', 'Packaging & Disposables', 5),
('RM1178', 'SALAD BOX', 'NOS', 'Packaging & Disposables', 5),
('RM1182', 'HAND WASH SOAP', 'LTR', 'Cleaning & Hygiene', 5),
('RM3024', 'FACE MASK', 'NOS', 'Cleaning & Hygiene', 5),
('RM3025', 'SANITIZER', 'BOT', 'Cleaning & Hygiene', 5),
('RM1183', 'TEEPOL (10 LTR CAN)', 'LTR', 'Cleaning & Hygiene', 5),
('RM3026', 'GLASS CLEANER', 'LTR', 'Cleaning & Hygiene', 5),
('RM3027', 'FLOOR CLEANER', 'LTR', 'Cleaning & Hygiene', 5),
('RM3028', 'DETOL 1 LTR', 'lTR', 'Cleaning & Hygiene', 5),
('RM1184', 'CLOROX (5 LTR CAN)', 'LTR', 'Cleaning & Hygiene', 5),
('RM3029', 'RINSO', 'KG', 'Cleaning & Hygiene', 5),
('RM1185', 'CUP CARRIER', 'NOS', 'Packaging & Disposables', 5),
('RM1186', 'LUNCH BOX BREAKFAST', 'NOS', 'Packaging & Disposables', 5),
('RM1179', 'VIM SOAP', 'NOS', 'Cleaning & Hygiene', 5),
('RM1180', 'SPONGE', 'NOS', 'Cleaning & Hygiene', 5),
('RM1181', 'CHOCOLATE CAKE CONTAINERS', 'NOS', 'Packaging & Disposables', 5),
('RM3030', 'PLASTIC BURGER BOX', 'BAGS', 'Packaging & Disposables', 5),
('RM1124', 'DELMA FLAVER TEA', 'KG', 'Beverages', 5),
('RM3031', 'STAFF TEA LEAVES', 'BAGS', 'Beverages', 5),
('RM1125', 'DELMA BLACK TEA', 'GRM', 'Beverages', 5),
('RM3032', 'CHAI SPICE', 'KG', 'Dry Groceries', 5),
('RM1151', 'FROZEN STRAWBERRY KG', 'PKT', 'Dry Groceries', 5),
('RM1117', 'MUNCHEE CHIP COOKIES', 'PKT', 'Dry Groceries', 5),
('RM1054', 'CORN FLOUR (200 GRM)', 'PKT', 'Bakery Raw', 5),
('RM1216', 'COOKING CREAM', 'NOS', 'Bakery Raw', 5),
('RM1135', 'SANDWICH BREAD LARGE', 'NOS', 'Bakery Raw', 5),
('RM1137', 'BREAD SUSANTHA LARGE', 'NOS', 'Bakery Raw', 5),
('RM1126', 'BROWN BREAD', 'NOS', 'Bakery Raw', 5),
('RM1127', 'SUB BUN', 'NOS', 'Bakery Raw', 5),
('RM1128', 'HOT DOG BUNS', 'NOS', 'Bakery Raw', 5),
('RM1129', 'BURGER BUNS', 'NOS', 'Bakery Raw', 5),
('RM1130', 'CIABATA BREAD', 'KG', 'Bakery Raw', 5),
('RM1201', 'BREAD CRUMBS', 'NOS', 'Bakery Raw', 5),
('RM1131', 'CHAPATHI', 'NOS', 'Bakery Raw', 5),
('RM1207', 'ROAT PAAN', 'NOS', 'Bakery Raw', 5),
('RM1213', 'PANINI BREAD', 'NOS', 'Bakery Raw', 5),
('RM1239', 'SMALL BURGER BUN', 'KG', 'Bakery Raw', 5),
('RM1132', 'FRENCH FRIES 2.5 KG', 'PKT', 'Dry Groceries', 5),
('RM1206', 'CRISPY CHICKEN POWDER', 'NOS', 'Bakery Raw', 5),
('RM1236', 'FOCCASIA BUN', 'NOS', 'Bakery Raw', 5),
('RM1133', 'PITA BREAD', 'KG', 'Bakery Raw', 5),
('RM1055', 'FLOUR', 'NOS', 'Bakery Raw', 5),
('RM1134', 'WAFFLES', 'KG', 'Bakery Raw', 5),
('RM1105', 'MILK POWDER LACKSPRAY-(1K)', 'PKT', 'Dairy', 5),
('RM1107', 'FETA CHEESE', 'GRM', 'Dairy', 5),
('RM1108', 'PARMASEN CHEESE (200 GRM)', 'SASET', 'Dairy', 5),
('RM1045', 'SUGAR SASETS', 'SASET', 'Dry Groceries', 5),
('RM1046', 'SOLO LOW CALIRY SUGR SASETS', 'KG', 'Dry Groceries', 5),
('RM1050', 'SUGER BULK (1K)', 'KG', 'Dry Groceries', 5),
('RM1051', 'CHIC PEAS', 'ROLL', 'Dry Groceries', 5),
('RM1154', 'CLIN FILM', 'PKT', 'Packaging & Disposables', 5),
('RM2004', 'BLACHAN', 'NOS', 'Dry Groceries', 5),
('RM3033', 'GREEN GRAM', 'NOS', 'Dry Groceries', 5),
('RM1043', 'EGG', 'KG', 'Meat & Poultry', 5),
('RM1052', 'PAPPER POWDER (100G)', 'PKT', 'Dry Groceries', 5),
('RM1098', 'PASTE SHELL (100G)', 'PKT', 'Dry Groceries', 5),
('RM1100', 'COCO POWDER (2.5K)', 'KG', 'Bakery Raw', 5),
('RM1049', 'RACING (250G)', 'PKT', 'Bakery Raw', 5),
('RM1101', 'BUTTER BEEHAIVE (1K)', 'KG', 'Dairy', 5),
('RM1122', 'CHESE SLICE', 'NOS', 'Dairy', 5),
('RM1122_2', 'CHESE SLICE KOTHMALE', 'NOS', 'Dairy', 5),
('RM1015', 'ANCHOVY FILLETS', 'TIN', 'Dry Groceries', 5),
('RM1102', 'COOKING CHOCOLAT', 'SLAB', 'Bakery Raw', 5),
('RM1047', 'PENUT (100G)', 'KG', 'Dry Groceries', 5),
('RM1048', 'SALT 400G', 'PKT', 'Dry Groceries', 5),
('RM1103', 'MOZARALLA CHESE( KG)', 'GRM', 'Dairy', 5),
('RM1057', 'CHILLIE PICES (200GRM)', 'KG', 'Dry Groceries', 5),
('RM1058', 'CHILIE POWDER (100G)', 'KG', 'Dry Groceries', 5),
('RM3034', 'MUSTERED SEED', 'PKT', 'Dry Groceries', 5),
('RM1059', 'TUMERIC', 'PKT', 'Dry Groceries', 5),
('RM1060', 'ROSEMARY', 'PKT', 'Dry Groceries', 5),
('RM1061', 'BASIL', 'PKT', 'Dry Groceries', 5),
('RM1062', 'ORIGANO', 'PKT', 'Dry Groceries', 5),
('RM1063', 'THYME', 'PKT', 'Dry Groceries', 5),
('RM1064', 'BAY LEAVES', 'PKT', 'Dry Groceries', 5),
('RM3035', 'VEGETABLE STOCK POWDER', 'TUB', 'Dry Groceries', 5),
('RM1044', 'CHICKEN STOCK POWDER', 'TUB', 'Dry Groceries', 5),
('RM1065', 'CUMMING POWDER (100 GRM PKT)', 'PKT', 'Dry Groceries', 5),
('RM1066', 'CARDAMOM (10G)', 'PKT', 'Dry Groceries', 5),
('RM1067', 'GARAM MASALA ( )', 'PKT', 'Dry Groceries', 5),
('RM1068', 'NUTMEG', 'NOS', 'Dry Groceries', 5),
('RM3036', 'PUFF SHEETS', 'SHEETS', 'Bakery Raw', 5),
('RM3037', 'MASTER PUFF - BEEHYFA BUTTER', 'KG', 'Bakery Raw', 5),
('RM3038', 'MEDOWLEA BUTTEER', 'KG', 'Bakery Raw', 5),
('RM3039', 'CROSSIANTS SHEETS', 'SHEETS', 'Bakery Raw', 5),
('RM3040', 'FLOUR', 'KG', 'Bakery Raw', 5),
('RM3041', 'BREAD IMPROOVER', 'KG', 'Bakery Raw', 5),
('RM3042', 'BAKING POWDER', 'PKT', 'Bakery Raw', 5),
('RM3043', 'YEAST', 'GRM', 'Bakery Raw', 5),
('RM3044', 'ICING SUGAR', 'PKT', 'Bakery Raw', 5),
('RM3045', 'CHOCOLATE VERMICELLY', 'GRM', 'Bakery Raw', 5),
('RM3046', 'RAINBOW VERMICELLY', 'GRM', 'Bakery Raw', 5),
('RM3047', 'DARK CHOCOATE', 'KG', 'Bakery Raw', 5),
('RM3048', 'WHITE CHOCOLATE', 'KG', 'Bakery Raw', 5),
('RM3049', 'CHOCOLATE CHIP', 'KG', 'Bakery Raw', 5),
('RM3050', 'COLORING', 'BOT', 'Bakery Raw', 5),
('RM3051', 'VANILLA SYRUP', 'BOT', 'Beverages', 5),
('RM3052', 'MIX SPICE', 'GRM', 'Bakery Raw', 5),
('RM3053', 'MARACHINO CHERRYS', 'BOT', 'Bakery Raw', 5),
('RM3054', 'WHIPPING CREAM', 'LTR', 'Dairy', 5),
('RM3055', 'RAISINS', 'GRM', 'Bakery Raw', 5),
('RM3056', 'DATES', 'KG', 'Dry Groceries', 5),
('RM3057', 'CAKE BOXES LG', 'NOS', 'Packaging & Disposables', 5),
('RM3058', 'CAKE BOXES SMALL', 'NOS', 'Packaging & Disposables', 5),
('RM3059', 'CAKE BOARDS ROUND', 'NOS', 'Packaging & Disposables', 5),
('RM3060', 'CAKE BOARDS SQUARE', 'NOS', 'Packaging & Disposables', 5),
('RM3061', 'DEMI PAPER', 'NOS', 'Packaging & Disposables', 5),
('RM3062', 'OIL PAPER', 'NOS', 'Packaging & Disposables', 5),
('RM3064', 'CAKE UNDERLINERS', 'NOS', 'Packaging & Disposables', 5);

-- 5. Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';
